<a href="https://colab.research.google.com/github/Desmond-dev12/Retail-analysis-web-App/blob/main/Retail_sales.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Retail Sales Analysis and Insights

* **Author:** **Desmond Pimpong**
* **Tooling:** **Python** || **Pandas** || **Plotly Express**

### 📌 Project Overview
This project analyzes a cleaned retail sales dataset to uncover key performance drivers across product lines, branch locations, and customer purchase behaviors. By evaluating transaction patterns and daily sales trends, the analysis highlights operational strengths, identifies revenue bottlenecks, and maps out sales volatility over time.

### 🎯 Primary Objective
The goal of this analysis is to perform Exploratory Data Analysis (EDA) to translate raw transaction data into actionable business strategies. Specifically, it aims to:
- Identify top-performing product categories and high-revenue store locations.
- Uncover peak buying windows across days of the week and dates.
- Provide data-driven recommendations to optimize inventory allocation, staffing schedules, and promotional strategies.

## 1. Data Inspection and Dataset Structure

**Before diving into visual analysis we perform a quick inspection to verify dataset:**
    
    1  Shape
    2. Data types
    3. Summary statitics

In [ ]:
 # Load and Inspect data

from google.colab import files
uploaded = files.upload()

Saving retail_store_clean.csv to retail_store_clean.csv

In [ ]:
import pandas as pd
import plotly.express as px

In [ ]:
data = pd.read_csv("retail_store_clean.csv")

In [ ]:
# Number rows and columns the dataset have

data.shape

(300, 12)

In [ ]:
# first 5 rows

data.head()

,Transaction ID,Store,Customer Type,Gender,Category,Unit Price,Quantity,Total,Date,Day,Payment,Rating
0,TXN-2424,West Hills Mall,Normal,Male,Electronics,81.02,3,255.21,2023-06-18,Saturday,Credit Card,8.4
1,TXN-9928,West Hills Mall,Member,Male,Cosmetics,73.41,1,77.08,2023-06-23,Saturday,Cash,7.4
2,TXN-6574,Kumasi City Mall,Normal,Female,Clothing,244.73,1,256.97,2023-06-14,Tuesday,Credit Card,8.6
3,TXN-1711,Kumasi City Mall,Member,Male,Clothing,36.90,2,77.49,2023-05-09,Wednesday,Mobile Money,6.2
4,TXN-4733,West Hills Mall,Member,Male,Cosmetics,170.09,6,1071.57,2023-01-02,Saturday,Mobile Money,7.5

In [ ]:
# data types

data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 12 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Transaction ID  300 non-null    object
 1   Store           300 non-null    object
 2   Customer Type   300 non-null    object
 3   Gender          300 non-null    object
 4   Category        300 non-null    object
 5   Unit Price      300 non-null    float64
 6   Quantity        300 non-null    int64
 7   Total           300 non-null    float64
 8   Date            300 non-null    object
 9   Day             300 non-null    object
 10  Payment         300 non-null    object
 11  Rating          300 non-null    float64
dtypes: float64(3), int64(1), object(8)
memory usage: 28.3+ KB

**Notice that this dataset is not fully cleaned after inspecting and must be cleaned fully in order to have accurate KPIs, Visualization and Analysis**

They are:


*   "Total" calculation is inconsistent
*   Wrong data type of "Date"

In [ ]:
data['Total'] = data['Quantity'] * data['Unit Price']

print(data[["Unit Price", "Quantity", "Total"]].head())

   Unit Price  Quantity    Total
0       81.02         3   243.06
1       73.41         1    73.41
2      244.73         1   244.73
3       36.90         2    73.80
4      170.09         6  1020.54

In [ ]:
#  wrong data type of Date to a correct data type

data['Date'] = pd.to_datetime(data['Date'], format="mixed")

data['Date'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 300 entries, 0 to 299
Series name: Date
Non-Null Count  Dtype
--------------  -----
300 non-null    datetime64[ns]
dtypes: datetime64[ns](1)
memory usage: 2.5 KB

In [ ]:
# Summary Statistics

data.describe()

       Unit Price    Quantity        Total                 Date      Rating
count  300.000000  300.000000   300.000000                  300  300.000000
mean   153.676167    4.526667   704.081600  2023-04-05 12:24:00    6.965000
min     10.320000    1.000000    26.270000  2023-01-01 00:00:00    4.000000
25%     81.895000    3.000000   242.767500  2023-02-21 18:00:00    5.500000
50%    154.155000    4.000000   535.675000  2023-04-11 00:00:00    7.000000
75%    222.652500    7.000000  1022.705000  2023-05-20 00:00:00    8.325000
max    299.990000    8.000000  2339.040000  2023-06-28 00:00:00   10.000000
std     81.287553    2.258234   555.185373                  NaN    1.699678

## 3. **Exploratory Data Analysis (EDA)**

In [ ]:
import plotly.express as px

In [ ]:
store_sales = data.groupby("Store")["Total"].sum().reset_index().round(2)
fig_store_sales = px.bar(store_sales, x="Store", y="Total",
                         title="Revenue by Store Sales",
                         text= "Total", color= "Store", text_auto=".2s",
                         color_discrete_sequence=px.colors.sequential.Viridis)
fig_store_sales.show()

In [ ]:
category_sales = data.groupby("Category")["Total"].sum().reset_index().round(2)
fig_category_sales = px.bar(category_sales, x="Category", y="Total",
                         title="Revenue by Category Sales",
                         text= "Total", color= "Category", text_auto=".2s",
                         color_discrete_sequence=px.colors.sequential.PuBu_r)
fig_category_sales.show()

In [ ]:
avg_category_sales = data.groupby("Category")["Rating"].mean().reset_index().round(2)
fig_avg_category_sales = px.bar(avg_category_sales, x="Category", y="Rating",
                         title="Average Rating by Category",
                         text= "Rating", color= "Category", text_auto=".2s" )

fig_avg_category_sales.show()

In [ ]:
Customer_sales = data.groupby("Customer Type")["Total"].sum().reset_index().round(2)

fig_customer_sales = px.pie(Customer_sales,
                         names="Customer Type",
                         values="Total",
                         title="Revenue by Customer Type",
                         color="Customer Type",
                         hole=0.4)
fig_customer_sales.show()

In [ ]:

monthly_sales = data.groupby("Date")["Total"].sum().reset_index().round(2)
fig_monthly_sales = px.line(monthly_sales, x="Date", y="Total", markers=True,
                         title="Daily Sales Trend", color_discrete_sequence=px.colors.sequential.Plasma
                        )
fig_monthly_sales.show()

In [ ]:
day_order= ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
data["Day"] = pd.Categorical(data["Day"], categories=day_order, ordered=True)
dail_sales_accross_week = data.groupby("Day")["Total"].sum().reset_index().round(2)
fig_dail_sales_accross_week = px.bar(dail_sales_accross_week, x="Day", y="Total",
                         title="Daily Sales Accross Week",
                         text= "Total", color= "Day",
                         text_auto= ".2s")
fig_dail_sales_accross_week.show()

/tmp/ipykernel_1172/3377942092.py:3: FutureWarning:

The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.

## 4. Key Business Insights & Actionable Recommendations

### 🔍 Key Business Insights
1. **Branch Revenue:** West Hills Mall leads total revenue (77k GHS), outperforming Kumasi City Mall (68k GHS) and Accra Mall (67k GHS).
2. **Top Product Lines:** Groceries (41k GHS) and Furniture (40k GHS) are the strongest revenue drivers, while Stationery (27k GHS) lags behind.
3. **Weekly Sales Patterns:** Revenue heavily spikes on Saturday (48k GHS) and Sunday (34k GHS), with an isolated mid-week surge on Wednesday (34k GHS).
4. **Customer Distribution:** Sales revenue is split almost evenly between Members (49.8%) and Normal customers (50.2%).

---

###  Actionable Business Recommendations
1. **Optimize Weekend Staffing & Checkout:** Maximize floor staff and open all checkout lanes on Saturdays and Sundays to handle high foot traffic and prevent cart abandonment.
2. **Launch Mid-Week Promotions:** Introduce targeted Monday and Thursday deals (e.g., discounts on Stationery or double loyalty points) to boost slow trading days.
3. **Buffer High-Demand Inventory:** Maintain higher safety stock levels for Groceries and Furniture ahead of weekends at West Hills Mall to avoid stockouts.
4. **Drive Member Loyalty:** Convert "Normal" shoppers into "Members" at checkout by offering exclusive instant discounts on top categories.

In [ ]:
data.to_csv("retail_store_clean.csv", index=False)